nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: BileMo
            description: This is an API for project 7 of the PHP/Symfony course on Openclassrooms
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc